### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by chrisgerman** [jay0lee/mbeg#1]
Hello,

I was wondering if your code still works before testing it out or adding it. Just wondering, we still have some old google meet codes roaming around that haven't expired. 

Thank you

**Comment by jay0lee** [comment]
I haven't tested it in done time but I'm not aware of any reason it would have broke. There's only one way to find out...

**Comment by jay0lee** [comment]
I've recently done some updates and testing:

- migrated to Google Chrome Extension Manifest v3 (MV3) for forward compatability as v2 is being deprecated.
- renamed to ubeg and made extension generic to any URL, not just Google Meet.
- few other bug fixes and corrections.

marking this as closed as this does still work :-)
